### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by chaishuanzhu** [KoonChaoSo/CSMixer#1]
"CSMixerAVFoundationCollector.h"
35行```self = [super init];```
>>self = [self init];

谢谢分享，学到了好多知识。

**Comment by KoonChaoSo** [comment]
谢谢，提醒在梳理中，下次更新会修复哈。。

**Comment by KoonChaoSo** [comment]
改了一下

**Comment by KoonChaoSo** [comment]
改了一下
